const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const seedDishes=[
 {id:'seed-fajitas',name:'Chicken Fajitas',ingredients:['Chicken breast','Tortillas','Bell peppers','Onion','Cheese','Sour cream'],favourite:true,source:'seed'},
 {id:'seed-bolognese',name:'Spaghetti Bolognese',ingredients:['Spaghetti','Beef mince','Onion','Garlic','Chopped tomatoes','Tomato puree','Italian herbs','Parmesan'],favourite:true,source:'seed'},
 {id:'seed-curry',name:'Chicken Curry',ingredients:['Chicken breast','Rice','Onion','Garlic','Ginger','Coconut milk','Curry powder'],favourite:false,source:'seed'},
 {id:'seed-burgers',name:'Burgers',ingredients:['Burgers','Burger buns','Cheese','Lettuce','Tomato','Onion'],favourite:false,source:'seed'},
 {id:'seed-roast',name:'Roast Chicken',ingredients:['Whole chicken','Potatoes','Carrots','Broccoli','Gravy'],favourite:false,source:'seed'},
 {id:'seed-lasagne',name:'Lasagne',ingredients:['Beef mince','Lasagne sheets','Onion','Garlic','Chopped tomatoes','Cheese','Milk'],favourite:false,source:'seed'}
];
const freshState=()=>({dishes:seedDishes,schedule:Object.fromEntries(DAYS.map(d=>[d,[]])),extras:[],shopping:[]});
let state=load();let editingId=null;let activeDay=null;
function load(){try{return {...freshState(),...JSON.parse(localStorage.getItem('food-schedule-v1'))}}catch{return freshState()}}
function save(){localStorage.setItem('food-schedule-v1',JSON.stringify(state))}
function id(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()}
function cleanName(s){return s.trim().replace(/\s+/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function uniqueIngredients(list){const seen=new Map();for(const raw of list){const n=cleanName(raw);if(n&&!seen.has(n.toLowerCase()))seen.set(n.toLowerCase(),n)}return [...seen.values()]}
function toast(msg){const el=document.querySelector('#toast');el.textContent=msg;el.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>el.hidden=true,2600)}
function render(){renderWeek();renderDishes();renderShopping();save()}
function renderWeek(){const grid=document.querySelector('#weekGrid');grid.innerHTML=DAYS.map(day=>`<article class="day"><h3>${day}</h3>${state.schedule[day].map((slot,i)=>{const dish=state.dishes.find(d=>d.id===slot.dishId);const title=slot.type==='dish'?(dish?.name||'Missing dish'):(slot.label||slot.type.replace('-',' '));return `<div class="slot"><div><strong>${esc(title)}</strong><small>${slot.type==='dish'?'Meal':esc(slot.type.replace('-',' '))}</small></div><button data-remove-slot="${day}|${i}" aria-label="Remove">×</button></div>`}).join('')}<button class="add-slot" data-day="${day}">+ Add</button></article>`).join('');
 document.querySelector('#extrasList').innerHTML=state.extras.map((x,i)=>`<span class="chip">${esc(x.name)} <small>${x.type}</small><button data-extra-remove="${i}">×</button></span>`).join('')}
function renderDishes(){const q=document.querySelector('#dishSearch').value.toLowerCase();const dishes=[...state.dishes].sort((a,b)=>Number(b.favourite)-Number(a.favourite)||a.name.localeCompare(b.name)).filter(d=>!q||d.name.toLowerCase().includes(q)||d.ingredients.some(i=>i.toLowerCase().includes(q)));document.querySelector('#dishGrid').innerHTML=dishes.map(d=>`<article class="dish-card" data-edit-dish="${d.id}"><span class="heart">${d.favourite?'♥':'♡'}</span><h3>${esc(d.name)}</h3><div class="ingredients">${d.ingredients.map(esc).join(' · ')}</div></article>`).join('')||'<p class="muted">No dishes found.</p>'}
function renderShopping(){const list=document.querySelector('#shoppingList');list.innerHTML=state.shopping.map((x,i)=>`<label class="shop-item ${x.checked?'checked':''}"><input type="checkbox" data-shop-check="${i}" ${x.checked?'checked':''}><span>${esc(x.name)}</span><button type="button" data-shop-remove="${i}">×</button></label>`).join('')||'<div class="shop-item"><span class="muted">Generate a list from your week, or add an item above.</span></div>'}
function generateShopping(){const existing=new Map(state.shopping.filter(x=>x.manual).map(x=>[x.name.toLowerCase(),x]));for(const day of DAYS)for(const slot of state.schedule[day])if(slot.type==='dish'){const dish=state.dishes.find(d=>d.id===slot.dishId);for(const ing of dish?.ingredients||[]){const k=ing.toLowerCase();if(!existing.has(k))existing.set(k,{name:ing,checked:false,manual:false})}}for(const x of state.extras){const k=x.name.toLowerCase();if(!existing.has(k))existing.set(k,{name:x.name,checked:false,manual:false})}state.shopping=[...existing.values()].sort((a,b)=>a.name.localeCompare(b.name));render();toast('Shopping list generated')}
function openDish(dish){editingId=dish?.id||null;document.querySelector('#dishDialogTitle').textContent=dish?'Edit dish':'New dish';document.querySelector('#dishName').value=dish?.name||'';document.querySelector('#dishIngredients').value=dish?.ingredients.join('\n')||'';document.querySelector('#dishFavourite').checked=!!dish?.favourite;document.querySelector('#deleteDishBtn').hidden=!dish;document.querySelector('#dishDialog').showModal()}
function openSlot(day){activeDay=day;document.querySelector('#slotTitle').textContent=`Add to ${day}`;document.querySelector('#slotType').value='dish';document.querySelector('#slotDish').innerHTML=[...state.dishes].sort((a,b)=>Number(b.favourite)-Number(a.favourite)||a.name.localeCompare(b.name)).map(d=>`<option value="${d.id}">${esc(d.name)}${d.favourite?' ♥':''}</option>`).join('');toggleSlotFields();document.querySelector('#slotDialog').showModal()}
function toggleSlotFields(){const type=document.querySelector('#slotType').value;document.querySelector('#slotDishWrap').hidden=type!=='dish';document.querySelector('#slotLabelWrap').hidden=!['custom','leftovers','takeaway','eating-out'].includes(type);const input=document.querySelector('#slotLabel');input.placeholder={leftovers:'Optional: leftovers from Monday',takeaway:'Optional: Pizza', 'eating-out':'Optional: Restaurant',custom:'e.g. Freezer meal'}[type]||''}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}

document.addEventListener('click',e=>{const tab=e.target.closest('[data-view]');if(tab){document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active'));tab.classList.add('active');document.querySelector('#'+tab.dataset.view).classList.add('active')}const add=e.target.closest('[data-day]');if(add)openSlot(add.dataset.day);const rem=e.target.closest('[data-remove-slot]');if(rem){const [day,i]=rem.dataset.removeSlot.split('|');state.schedule[day].splice(+i,1);render()}const edit=e.target.closest('[data-edit-dish]');if(edit)openDish(state.dishes.find(d=>d.id===edit.dataset.editDish));const er=e.target.closest('[data-extra-remove]');if(er){state.extras.splice(+er.dataset.extraRemove,1);render()}const sr=e.target.closest('[data-shop-remove]');if(sr){state.shopping.splice(+sr.dataset.shopRemove,1);render()}});
document.addEventListener('change',e=>{if(e.target.matches('[data-shop-check]')){state.shopping[+e.target.dataset.shopCheck].checked=e.target.checked;renderShopping();save()}});
document.querySelector('#dishSearch').addEventListener('input',renderDishes);document.querySelector('#newDishBtn').onclick=()=>openDish();document.querySelector('#generateBtn').onclick=generateShopping;document.querySelector('#slotType').onchange=toggleSlotFields;
document.querySelector('#dishForm').addEventListener('submit',e=>{e.preventDefault();const dish={id:editingId||id(),name:cleanName(document.querySelector('#dishName').value),ingredients:uniqueIngredients(document.querySelector('#dishIngredients').value.split('\n')),favourite:document.querySelector('#dishFavourite').checked,source:editingId?(state.dishes.find(d=>d.id===editingId)?.source||'user'):'user'};if(editingId)state.dishes=state.dishes.map(d=>d.id===editingId?dish:d);else state.dishes.push(dish);document.querySelector('#dishDialog').close();render()});
document.querySelector('#deleteDishBtn').onclick=()=>{if(!editingId)return;state.dishes=state.dishes.filter(d=>d.id!==editingId);for(const day of DAYS)state.schedule[day]=state.schedule[day].filter(s=>s.dishId!==editingId);document.querySelector('#dishDialog').close();render()};
document.querySelector('#slotForm').addEventListener('submit',e=>{e.preventDefault();const type=document.querySelector('#slotType').value;state.schedule[activeDay].push({type,dishId:type==='dish'?document.querySelector('#slotDish').value:null,label:type==='dish'?'':document.querySelector('#slotLabel').value.trim()});document.querySelector('#slotLabel').value='';document.querySelector('#slotDialog').close();render()});
document.querySelector('#addExtraBtn').onclick=()=>{const input=document.querySelector('#extraInput');if(!input.value.trim())return;state.extras.push({name:cleanName(input.value),type:document.querySelector('#extraType').value});input.value='';render()};
document.querySelector('#addShopBtn').onclick=()=>{const input=document.querySelector('#customShopInput');if(!input.value.trim())return;state.shopping.push({name:cleanName(input.value),checked:false,manual:true});input.value='';render()};
document.querySelector('#clearCheckedBtn').onclick=()=>{state.shopping=state.shopping.filter(x=>!x.checked);render()};
document.querySelector('#importBtn').onclick=async()=>{const btn=document.querySelector('#importBtn');btn.disabled=true;btn.textContent='Importing…';try{const letters='abcdefghijklmnopqrstuvwxyz'.split('');const all=[];for(const letter of letters){const r=await fetch(`https://www.themealdb.com/api/json/v1/1/search.php?f=${letter}`);if(!r.ok)throw new Error('API error');const data=await r.json();all.push(...(data.meals||[]))}const byName=new Map(state.dishes.map(d=>[d.name.toLowerCase(),d]));let added=0;for(const meal of all){const ingredients=uniqueIngredients(Array.from({length:20},(_,i)=>meal[`strIngredient${i+1}`]).filter(Boolean));if(!meal.strMeal||!ingredients.length)continue;const name=cleanName(meal.strMeal);if(!byName.has(name.toLowerCase())){const dish={id:`mealdb-${meal.idMeal}`,name,ingredients,favourite:false,source:'themealdb',sourceId:meal.idMeal};state.dishes.push(dish);byName.set(name.toLowerCase(),dish);added++}}render();toast(`Imported ${added} new dishes`)}catch(err){console.error(err);toast('Import failed — starter dishes are still available')}finally{btn.disabled=false;btn.textContent='Import TheMealDB'}};
render();
